export const FETCH_DATA = 'FETCH_DATA';
export const FILTER_TEXT = 'FILTER_TEXT';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
